### ISSUE TITLE
Study Azure QnA Maker

### ISSUE THREAD

**Issue by andersonfurtado** [andersonfurtado/UdacityAMAchatBot#7]
1. Microsoft Learn - QnA Maker
2. Microsoft video - QnA Maker

**Comment by andersonfurtado** [comment]
**1. Create azure account** https://azure.microsoft.com/en-au/free/
https://docs.microsoft.com/id-id/learn/modules/create-an-azure-account/

**2. Azure QnA Maker** https://azure.microsoft.com/en-us/services/cognitive-services/qna-maker/
https://www.youtube.com/watch?reload=9&v=sxy9ZTC3BhA

**Comment by lambertsbennett** [comment]
Happy to learn more about this to help out the project.

**Comment by andersonfurtado** [comment]
> Happy to learn more about this to help out the project.

Welcome, @lambertsbennett!

**Comment by ldandrade** [comment]
Just to keep track more easily.

- [ ] ldandrade
- [ ] arishuynhvan
- [ ] KC2016
- [ ] abitaaugustine
- [ ] claudiabringaseverett
- [x] andersonfurtado
- [x] bnuratum
- [x] lambertsbennett
